### PR TITLE
Heavy trooper starting gear redux

### PR DESCRIPTION
**Pull request by spockye**
## About The Pull Request

this PR does one thing
it replaces the Flamethrower (which barely worked) with the now Nerfed minigun

Why?
nobody uses the flamethrower kit, due to it being mostly non-functional
## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
tweak: Replaced the HT flamethrower with a minigun
/:cl:

### CODE REVIEW

**Comment by CUST-0M** [comment]
This is too good for HT, especially the super sledge AND hunting revolver sidearm they get in the melee loadout.

**Comment by Teragenic** [comment]
Hunting revolver does 45? Damage and has a 1600ms cooldown, they are wearing SPA. If they get into sledging range, it's more of a positioning issue.

I'm pretty sure the minigun does inline or less than 9mm, ever since the nerfs. 

So the choices are for the HT: Decent 5.56 LMG, bees of death minigun(essentially a better american 180), and a melee-hunting revolver build... Which means you need to put points into melee and guns. Hunting revolver isn't even that good :P

**Comment by spockye** [comment]
Not mentioning the fact that the spa gives immense slowdown making actually getting in melee range HARD.

**Comment by YosemiteYam** [comment]
You’re not getting a super sledge for HT lol, its the best melee weapon in the game/highest tier loot. 

A melee build is fine but be more realistic with what you’re asking for chum

**Comment by spockye** [comment]
> You’re not getting a super sledge for HT lol, its the best melee weapon in the game/highest tier loot.
> 
> A melee build is fine but be more realistic with what you’re asking for chum

Personally dont see much of a issue with it. Seeing that paladins get em', plus powerfists. 
AND since its what they use in NV

what do you think is a better alternative

**Comment by CaputCapital** [comment]
I know HTs in NV are given super sledges but for what this PR intends, it may only end up being counter-intuitive for the fact that they wear SPA that slows them down significantly. Any character fast enough would most likely juke out the HT before the HT can score a single hit on their attacker.

The reason why people don't use the flamethrower kit is because they don't know how to make the flamethrower fuel, which you would think an NCR engineer would but you never see NCR engineers doing that. Therefore the task ends up being delegated to the HT, so long as they know how much repair skill they need.

**Comment by RicktenStone** [comment]
Legionaries also spawn with super sledges in their hit squads in FNV but I believe the supersledge was removed by the only role in the legion that had it (veteran decanus) so I don't think its fair if HT's got one.

**Comment by spockye** [comment]
Melee kit removed, due to feedback

**Comment by BadAtThisGame302** [comment]
>nobody uses the flamethrower kit, due to it being mostly non-functional

I just saw it work in action, @CaputCapital can confirm because he set 3 Legionaries on fire with the flamethrower. Don't know why you say it's non-functional?

**Comment by CaputCapital** [comment]
> > nobody uses the flamethrower kit, due to it being mostly non-functional
> 
> I just saw it work in action, @CaputCapital can confirm because he set 3 Legionaries on fire with the flamethrower. Don't know why you say it's non-functional?

I can confirm this. It's not broken, it's just that there's no spread or recoil on the M2 flamethrower.

**Pull request closed without merging**
