### PR TITLE
Blythe Vault Update

### PR DESCRIPTION
**Pull request by gurking**
## About The Pull Request

Brings back the old circular Vault with some updates.
image

New is specifically an internal mining access, an Overseer/CoS exclusive atrium, and a second entrance to the Vault underground near the legion/various bunkers (time-locked).
image
image
Removes the shop. It's awful.

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
map: Vault
/:cl:

### CODE REVIEW

**Comment by AllCorruptingWyrm** [comment]
I just ascended.

**Comment by BadAtThisGame302** [comment]
I just jizzed my pants finding out the Vault has no shop anymore.

+1

**Review by spockye — CHANGES_REQUESTED** [review]
image

cabling errors

image

turf errors

image

why is this wire here

image

why is this wire here

image

why is this wire here

image

why do they get a excavator power helmet, and a PA book

image

airless asteroid turf?

image

missing corner decals

image

floating camera. Armoury seems a bit too well stocked, no?

image

could use some threats around here. molerats/ ghouls/ ants

**Comment by gurking** [comment]
image
Addressed the feedback.

**Comment by AsterixCodix** [comment]
So, what's in the armoury?

Precisely what happened with the Excavator PA?

What's in place to stop shitters from overloading the reactor?

What's with the two full Borg bodies?

Please tell me that's not the old tier 5 weapon spawner hidden away in the prison.

**Comment by gurking** [comment]
> So, what's in the armoury?

1 Trench Shotgun, 2 AER9, 4 Wattz pistols, 2 NVGs, 2 Flashbangs, 2 Teargas grenades, 2 Swat Combat Helmets, 2 Swat Combat Maks, 4 Police batons, Energy Ammo, 3 Barrier grenades

> Precisely what happened with the Excavator PA?

Removed.

> What's in place to stop shitters from overloading the reactor?

They are generators that can't explode.

> What's with the two full Borg bodies?

They are Borg spawners.

> Please tell me that's not the old tier 5 weapon spawner hidden away in the prison.

It was an armory contraband spawner, but I think that's deprecated anyway, so I removed it.

**Comment by Zero-Percent-Angel** [comment]
> > > So, what's in the armoury?
> > 
> > 
> > 1 Trench Shotgun, 2 AER9, 4 Wattz pistols, 2 NVGs, 2 Flashbangs, 2 Teargas grenades, 2 Swat Combat Helmets, 2 Swat Combat Maks, 4 Police batons, Energy Ammo, 3 Barrier grenades
> > > Precisely what happened with the Excavator PA?
> > 
> > 
> > Removed.
> > > What's in place to stop shitters from overloading the reactor?
> > 
> > 
> > They are generators that can't explode.
> > > What's with the two full Borg bodies?
> > 
> > 
> > They are Borg spawners.
> > > Please tell me that's not the old tier 5 weapon spawner hidden away in the prison.
> > 
> > 
> > It was an armory contraband spawner, but I think that's deprecated anyway, so I removed it.
> 
> I would ask that the Batons are also removed. Does it make sense to have them? Yes. But stun combat is abysmal and over powered at the moment and would rather not have anything to support it

I think regular batons are alright stun batons tend to be the abusive ones but perhaps I'm wrong

**Comment by Omnisalad** [comment]
God bless. I take it this means the Vault has to go through the train station to get to the surface now?

**Comment by gurking** [comment]
> God bless. I take it this means the Vault has to go through the train station to get to the surface now?

There's the train station entrance to the west of the NCR and a big cave system that leads to the old Vault-Tec museum near the legion.

**Comment by Knightfall5** [comment]
The wrong Vault wall is used extensively along the outer edges. The indestructible vault wall is the exterior wall, you can simply deconstruct your way into the Vault from multiple different directions.

**Comment by Serxule** [comment]
> I would ask that the Batons are also removed. Does it make sense to have them? Yes. But stun combat is abysmal and over powered at the moment and would rather not have anything to support it

normal batons are horribly awful for even trying to detain someone lol, only stun batons (unobtainable) are broken in combat

**Comment by Knightfall5** [comment]
> > The wrong Vault wall is used extensively along the outer edges. The indestructible vault wall is the exterior wall, you can simply deconstruct your way into the Vault from multiple different directions.
> 
> Intended.

Why wasn't this mentioned in the title then? It's incredibly bad faith to sneak in changes like this without documenting them, it's completely impossible to defend the vault now. This PR should be denied if this isn't changed since it cripples the Vault's defenses.

**Pull request merged**
