### PR TITLE
Adds two energy guns to the premium weapon list

### PR DESCRIPTION
**Pull request by spockye**
## About The Pull Request

This PR adds the laser RCW smg, and the wattz_2000e to the Premium list
Energy weapons need some love 🥺 
## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
add: Adds Laser rcw and wattz_2000e to Premium pack options
/:cl:

### CODE REVIEW

**Comment by AllCorruptingWyrm** [comment]
if I might, do you think you could give premium weapon list stuff to the HP instead of the Head Scribe?

thank you!!

**Comment by spockye** [comment]
thats a bit out of scope for this PR, sorry!

**Comment by Stutternov** [comment]
The Wattz 2ks is a unique weapon, not the extended version.

**Comment by spockye** [comment]
No work is needed on the pr

**Comment by spockye** [comment]
please un-stale 
image

**Pull request merged**
