### PR TITLE
Medicine rebalance (bear and bull made equal)

### PR DESCRIPTION
**Pull request by CUST-0M**
## About The Pull Request
Makes it so that tribal fallout medicine is as good as regular fallout medicine, for bear bull purposes. It changes the name of stimfluid so that scanners won't show "stimfluid" when the bitters women scan a legionary, then makes poultice functionally identical to stims. The same is done with bitter drinks where the old poultice reagent stays the same and is renamed to bitter drink, and made equal with super stims. Instant heals are removed entirely because lol whose idea was that. Overall healing values stay almost the same, with a slight increase.

Forgot to mention this:
The recipes for tribal medicine have been updated as well to match stims and super stims. The tribal variants are a bit more expensive. The level of outdoorsman required to craft bitter drinks and poultices has been increased to the next tier for each as well.

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
del: instant heal on stimfluids
tweak: poultice reagent renamed to bitter drink
tweak: added stim fluid, now renamed "medical fluid" to poultices
tweak: changed the properties of super stim fluid to be similar to the old poultice reagent
tweak: increased the outdoorsman levels needed to craft poultice and bitters to match stims and super stims
tweak: lowered the OD threshold for stim fluid to prevent muh prestimming with the higher heal rates.
balance: made bitter drinks function similarly to super stims
balance: made poultice function similarly to stims
/:cl:

### CODE REVIEW

**Comment by X404ErrorX** [comment]
I like the pr, it's something necessary, I would like to know if it would be possible for tribal medicine to be used through the helmet, it's not fun having to remove your helmet and mask in middle of a fight to be able to heal yourself.

**Comment by CUST-0M** [comment]
> I like the pr, it's something necessary, I would like to know if it would be possible for tribal medicine to be used through the helmet, it's not fun having to remove your helmet and mask in middle of a fight to be able to heal yourself.

healing poultice can be used through a mask, bitter drink cannot. healing poultice is the one with no slowdown now so it should be alright

**Comment by YosemiteYam** [comment]
Good PR, was much needed. Tell me, does this also remove the application delay for tribal meds? Because stimpacks can be used instantly on the move while tribal meds require you to stop and use it, which is detrimental in combat and one of the main issues that made it imbalanced.

**Comment by CUST-0M** [comment]
> Good PR, was much needed. Tell me, does this also remove the application delay for tribal meds? Because stimpacks can be used instantly on the move while tribal meds require you to stop and use it, which is detrimental in combat and one of the main issues that made it imbalanced.

Yeah, the delays are removed.

**Comment by CUST-0M** [comment]
I forgot to mention the changes to the recipes. Description updated.

**Comment by CUST-0M** [comment]
remaking this to be better

**Pull request closed without merging**
