### PR TITLE
Energy Rebalance: Ballistics just weren't enough....

### PR DESCRIPTION
**Pull request by maaacha**
## About The Pull Request
Energy weapons weren't bad, but they weren't very unique and didn't serve a niche. They were basically mid-tier ballistics with hitscan - not even hitscan in the case of the plasma rifle. This PR looks to fix up some of the underpowered energy weapons and increase uniqueness in the blander firearms.

Specifically, the AER weapons were all basically the same gun, a mid-tier rifle. This stages out the guns so they have some uniqueness and variance; the AER9 fills the role of a basic low tier laser gun with 8% AP, 25 shot MFC capacity and a meh fire rate. The AER12 fills the role of a mid-tier laser gun specialized in armour penetration, dealing significantly higher AP at 20%, but having 10 less ammunition per MFC than the AER9. The AER14 is the high tier laser gun, with a higher fire rate than both prior guns, 20% AP and 20 shots per MFC. Furthermore, the Laser RCW has been given 5% armour penetration to offset the comparatively low damage (when compared to other mid to high tier SMGs) and bring it in line with other energy weapons.

Other changes include some speeding up of the plasma projectile so it isn't insanely easy to dodge for anyone with four fingers on their left hand, a buff of the chew chew's armour penetration to be actually high to justify it's insanely low damage.

Additionally, for some reason the YK pulse rifle (ion rifle) had like 15 shots per MFC, an insane fire rate, good damage and 75% armour pen. It's been nerfed slightly, as well as having it's ion radius fixed so it doesn't drain energy cells on the user.

The Wattz 2000 has been given slowdown and fire rate in line with similar sniper rifles.

If you want exact numbers on how many shots a specific gun takes to kill against specific armours, feel free to message me.

ADDENDUM: Tribeam, multiplas and laserbuss fixed. Ignore the insane recoil values, it's the only way for it not to be deadeye accurate every shot with 100 energy weapons. Also, base damage was lowered on all energy weapons to accommodate for the realization that they have no recoil. Adjustments are pretty marginal, and bring laser weapons in line with the improvised ammunition types for weapons of their equivalent.

## Pre-Merge Checklist
- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog
:cl:
fix: Tribeam is no longer perfectly accurate.
fix: Multiplas is no longer perfectly accurate.
fix: Laserbuss is no longer perfectly accurate.
fix: YK ion radius changed from 2 to 1 so it doesn't drain user's energy cells.
balance: YK MFC capacity changed from 15 to 10, armour pen from 75% to 60%, damage from 28 to 25.
balance: AER9 armour pen increased from 2% to 8%
balance: AER12 fire rate increased, AP decreased from 55% to 20%, shot count increased from 8 to 15
balance: AER14 fire rate increased, AP increased to 20%, shot count increased from 15 to 20
balance: Chew-chew given 75% AP to make up for shooting literal piss lasers (13 damage lol).
balance: RCW given 5% AP
balance: Plasma projectiles sped up slightly
balance: Wattz 2000 lowered fire rate + increased slowdown to make it an actual sniper instead of a rifle.
balance: Lowered overall base damage to accommodate for the lack of recoil in all energy weapons.
/:cl:

### CODE REVIEW

**Comment by YosemiteYam** [comment]
I feel like nerfing the pulse rifle capacity to just 6 shots is too much, its not practical for anything outside of emping someone using energy weapons anyway, 6 shots makes it even tougher to land a hit on energy weapon users to emp them and effectively becomes a BoS buff.

**Comment by ToastyWiz** [comment]
Yeah, most of this feels pointless seeing as energy weapons weren't really that bad in the first place.

Also? Why are you removing EMP arrows?

**Comment by maaacha** [comment]
> Yeah, most of this feels pointless seeing as energy weapons weren't really that bad in the first place.
> 
> Also? Why are you removing EMP arrows?

What purpose do they serve outside of nerfing a weapon that is mid-tier at best? Also the AER9 was in a pretty fine place, which is why it has been barely touched. The AER12 and AER14 had literally the same stats, more or less, and therefore god buffed to _actually_ fill their role of mid and high tier laser weapons. Read the PR's description next time.

**Comment by spockye** [comment]
If your decreasing the charges on the pulse gun, atleast increase its damage against power armour. Currently it feels like it deals basically nothing

**Comment by Zero-Percent-Angel** [comment]
Certainly worth taking a look at the CI here it's really not happy, some of the changes must be breaking

**Comment by maaacha** [comment]
> Certainly worth taking a look at the CI here it's really not happy, some of the changes must be breaking

missed a typo should be fixed

**Pull request merged**
