### PR TITLE
Finally, Armor?????

### PR DESCRIPTION
**Pull request by Stutternov**
## About The Pull Request
Yeah, fixes reported errors. Tribal armors, NCR ranger armor being the wrong helmet, etc.

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog
:cl:
fixes: More armor sprite fixes
fixes: Repaths tribal sprite thus fixing pathing errors.
/:cl:

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
Third time's the charm!

**Comment by Stutternov** [comment]
Still testing this.

**Comment by Stutternov** [comment]
Right - tested, it's working. Merge whenever; I'll be updating sprites as I go.

**Comment by Stutternov** [comment]
Ready

**Pull request merged**
