### PR TITLE
Nerfs Ion arrow and EMP grenade availability

### PR DESCRIPTION
**Pull request by HanSolo1519**
## About The Pull Request
Ion arrows were incredibly busted, providing an EMP for 2 electronic parts. As opposed to removing them, they have been nerfed to require an MFC per arrow.
EMP Grenades have been removed from the advanced ammo book and placed in their own dedicated crafting blueprint, shoved in the high tier blueprint loot table, aswell as removed from camp follower and logistical officer (rip LO o7) inheret job traits, aswell as taken from the t2 bomb loot pool. They're now a rare find, instead of a medium-rare one.

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog
:cl:
balances: above mentioned recipies
/:cl:

### CODE REVIEW

**Comment by YosemiteYam** [comment]
Making emp grenade just blueprint based instead of advanced explosives book based is a needless nerf, what is this, the BoS coder mafia back in town?

**Comment by CUST-0M** [comment]
EMPs are the only (minor) downside to energy guns. Otherwise, they are better than ballistics in every way. The change makes no sense either, it's an advanced explosives book so it should have advanced explosives.

**Comment by SingingSpock** [comment]
100% agree with the ion arrow change, but the grenade change is very unnecessary and feels like trying to buff weapons that don't need to be buffed.

**Comment by BigBigga** [comment]
BOS cabal back at it again

**Pull request closed without merging**
