### PR TITLE
Changes Paladin-Slayer Loadout

### PR DESCRIPTION
**Pull request by DovaKitty**
## About The Pull Request
This PR changes the Paladin-slayer loadout for Centurion to focus on energy weapons instead of ballistics. It also adds a shoulderholster to Centurion, to bring it in line with other recently-changed Legion roles. Tested ingame, but I'm unable to actually use the loadouts due to webui. I think it will work perfectly, but please try to test on the actual server if possible before merging to main, thanks.

-But Dova, what about balance?
Glad you asked. This PR brings Paladin-slayer cent about to the same level of strength as the Brotherhood's Head Scribe role. Order of the Shield Head Scribe currently gets Salvaged Power Armor, a selectable AMR and a glock pistol. As the plasma rifle is not as strong as the AMR, this loadout for centurion will still be below the power of one of the Brothehrood's non-combat roles. I think it's a good place for the strongest member of the Legion balance wise. Through my testing, the plasma rifle has a higher Time to Kill on all grades of armor than the AER12, which is given to Senior Paladins.

-But Dova, what about lore?
While some people believe the Legion would be unwilling or unable to use energy weapons, this is actually not the case in lore. One quest follows the Legion attempting to buy a large supply of energy weapons from the Van Graffs (presumably plasma rifles). It seems the main reason we do not see the Legion use energy weapons in Fallout:NV is due to their inability to supply them as they are rare in the setting. The Paladin-slayer loadout is for Centurions who have killed at least one Paladin in direct combat. This could easily explain how they in particular got their hands on rare energy weapons. Complaints about the Legion's ability to maintain advanced energy weapons through multiple battles can easily be counted by the Fiends, a horde of drug addicts who use tons of plasma weaponry.

-But Dova, what about flavor?
While it is true that energy weapons buck the trend of the Legion using bolt action or automatic ballistics, I don't think this is necessarily a bad thing. Plasma weapons, except for the glock, are not given roundstart to any role in the game. This is not due to balance, as plasma weapons are balanced similarly to laser weapons, but simply for flavor reasons. If the Legion were to use an energy weapon, I think it would be best if they used the rarer type (plasma), as their theme on F13 is to use more unorthodox weapons. Giving Paladin-Slayer plasma weapons would allow them to be seen far more outside of someone making plasma rifles from a blueprint 2 hours into a round. It would also help differentiate the loadout from the other two (both ballistic-based).

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl: Dova
-Changes the Paladin-Slayer loadout option for Centurion to use energy weapons instead of ballistics.
/:cl:

### CODE REVIEW

**Comment by DovaKitty** [comment]
MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE

**Comment by BadAtThisGame302** [comment]
So you gonna give the BAR to the normal centurion loadout or just completely remove it? (With a plasma rifle which I honestly think is worse than the gun you replaced it with.)

**Comment by Serxule** [comment]
1. plasma rifle is dogshit
2. ammo is a massive problem

**Comment by Serxule** [comment]
also i should add, this would force cents to take energy skill to even use the loadout, energy skill being nigh useless as legion, this is a really bad change

**Comment by DovaKitty** [comment]
> So you gonna give the BAR to the normal centurion loadout or just completely remove it? (With a plasma rifle which I honestly think is worse than the gun you replaced it with.)

I think you're right that the BAR is stronger and more thematic than what normal cent gets right now. Unless people really like the 14mm pistol, I'll move it over there.

**Comment by DovaKitty** [comment]
Making the executive decision to close this PR and reopen it with changes. Plasma rifle is not strong enough for faction leader, and the BAR will have to be put somewhere. I am thinking about plasma caster and vet decan's heavy loadout respectivly. Soon.

**Pull request closed without merging**
