### PR TITLE
Perks and Drugs and Rock and Roll

### PR DESCRIPTION
**Pull request by AsterixCodix**
## About The Pull Request

Fixes a bug that lets you take every health-related perk; adds in a bunch of different goth/scav/misc clothing for the _aesthetics_; adds in a bunch of Lancer clothes (mostly sprites) for possible future use. It also: makes Cold Blooded a positive Quirk, instead of a Negative one; Reworked Deadeye so it still fits the description and overall concept, but functions differently; nerfed Turbo; removed nerfed GetAway and removed references to Skooma/Moonsugar in the code (this isn't a TES server). Further, it: adds in Robot Workbench sprites for the exosuit fabricator; adds in grass tiles because, _variety_; adding in a Ham Radio sprite just... Because; adding a sprite for bloodleaf too, just for the hell of it; added sprites for a new hairstyle (yet to be implemented); PA workbench sprites; nerfs the interactions between Big Leagues and Buffout (that worked in testing). Also provides; sprites for the SCAV! Magazines; everything required to implement Pain Train, but as I can't quite figure it out yet, doesn't add the perk; adds a bunch of the clothing items to the Custom Loadout menu and restructures the back end.

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
add: Readded the perk Deadeye
add: Adds the framework for the Pain Train perk
fix: fixed Health Perks not locking other Health Perks
tweak: tweaked Deadeye
balance: buffed Buffout's damage buff
balance: nerfed Big Leagues/Buffout interaction

tweak: Custom Loadout Menu using inheritance

add: Added a scarlet coat
add: Added new Poncho sprites
add: Added black and white turtleskirt
add: Added black and white striped turtleskirt
add: Added black, white and pink turtleskirt
add: Added black and pink turtleskirt
add: Added grey and white turtleskirt

add: Added Lancer pilot jacket
add: Added new sprites for the Recon Suit
add: Added Lancer flight cap
add: Added Lancer flight soft hat
add: Added Lancer flight suit

add: Added grass turfs
add: Added grass corner turfs
add: Added grass/dirt path turfs
add: Added ham radio sprites
add: Added PA work station sprites
add: Added new Exosuit Fabricator sprites
add: Added bloodleaf sprites

add: Added goth jacket
add: Added goth outfit
add: Added goth outfit (female)
add: Added goth outfit (skimpy)
add: Added goth outfit (female, skimpy)
add: Added gothic choker

add: Added high heels
add: Added thigh high boots
add: Added thigh high platforms
add: Added thigh high stilettos
add: Added blue thigh high boots
add: Added blue thigh high platforms

add: Added scavvers gear
add: Added scavvers gear (female)

tweak: tweaked Moonsugar
balance: rebalanced Turbo
balance: rebalanced GetAway
removes: removed crocin
removes: removed hexacrocin
removes: removed furranium
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
coldblooded is definitely not a positive perk because bloodloss is barely an issue

**Comment by AllCorruptingWyrm** [comment]
Asterix I was joking about the lancer thing

asterix.

**Comment by FantasticFwoosh** [comment]
This is a horrible unatomized mess. I would close this immediately (much least for being a merge conflict extreme 🚩)

Other than that, only technical thing i want to point out, is that paintrain is currently commented out.

**Comment by AsterixCodix** [comment]
> This is a horrible unatomized mess. I would close this immediately (much least for being a merge conflict extreme 🚩)
> 
> Other than that, only technical thing i want to point out, is that paintrain is currently commented out.

Pain Train is... Gonna be an actual headache to fully implement, so it's staying commented out until I can figure it out properly. 

Admittedly, this did kinda sprawl further than I'd intended, initially.

**Comment by X404ErrorX** [comment]
I like the pr, more perks sounds like more variety which makes everything more fun, by the way, Cold blood is a pretty negative perk, if for some event your character suffers from cold prepare for a MASSIVE slowdown.

**Comment by panzerr1944** [comment]
Deadeye got uncommented, but you removed what deadeye actually did- so its 5 points lost with no benefit as it stands.

**Pull request merged**
