### PR TITLE
town requests implementation

### PR DESCRIPTION
**Pull request by cornercube**
## About The Pull Request

citizen spawns moved out of private rooms

wooden flooring removed in many parts

a tiny ghetto added in the back

some rooms unique-ified

Reflection3
Reflection3

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
tweak: blythe surface and above
/:cl:

### CODE REVIEW

**Comment by Zero-Percent-Angel** [comment]
Did you remember to adjust all the roofs?

**Comment by cornercube** [comment]
> Did you remember to adjust all the roofs?

Reflection3

the only part of the building i extended should be covered by a roof alreadty

**Comment by cornercube** [comment]
> Got some conflicts on this otherwise once they're done I'll merge it into Dev

it looks like it over wrote some previous mapping changes from the a recent mapping PR that came before. so it needs to merge the two

**Comment by cornercube** [comment]
hopefully that re-adds the changes from #92  that got overwritten

**Comment by cornercube** [comment]
> @cornercube is the map for this looking okay? No stuff been reverted right?

the conflicts should be resolved now, i manually inputted the overwritten parts

**Pull request merged**
