### PR TITLE
Vault Remake 

### PR DESCRIPTION
**Pull request by spockye**
## About The Pull Request

This pr fully remakes the Vault, and slightly changes the area around it. 

This pr SHOULD NOT BE MERGED, ONLY TESTMERGED (ignore this. It should be fine)
--
the vault's going to be used on the new map, and I'd like some player feedback. 

image

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
add: Fully remakes the Blythe vault
/:cl:

### CODE REVIEW

**Comment by Zero-Percent-Angel** [comment]
Just a few questions on this, the dorms any particular reason we don't want the doors to have the lock button on them?
Same with the bathroom no lock?
Also the Overseer's room looks more dinky than even the regular vault rooms which seems a bit harsh.
We probably shouldn't have glowing goop in one of the bedrooms too.

**Comment by spockye** [comment]
image

new bedroom

image

goopless-locked bedrooms and restroom

**Comment by spockye** [comment]
should be fine to merge

**Comment by Zero-Percent-Angel** [comment]
Do we still need this if we've got Tipton ready for a test merge? @spockye 
It's the Vault on Tipton if I remember rightly?

**Comment by spockye** [comment]
If we still want to use blythe, id say yes

**Comment by spockye** [comment]
Wont be able to work on this for a while

**Comment by spockye** [comment]
Gwa

**Pull request closed without merging**
