### PR TITLE
Explorer SKS

### PR DESCRIPTION
**Pull request by AllCorruptingWyrm**
## About The Pull Request
The Legion Explorers got an M1 instead of an SKS. This PR fixes that.

## Pre-Merge Checklist
- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog
:cl:
add: legion SKS
/:cl:

### CODE REVIEW

**Comment by Stutternov** [comment]
That was intentional. If you look.. that's not even an M1 Garand, it's a hunting rifle.

That is purposeful because semi-auto 7.62s round start are powerful especially on a role that is not an elite role and equal to Prime.

**Comment by DaemonTinadel** [comment]
Seeing as Rangers somehow kept their R91s/Snipers/10mm smgs. It is a bit unfair that the Explorers are more or less given horrible guns. I'm not sure why this happened as I thought EVERYONES loadouts were being nerfed not one faction and frankly thats how it seems.

**Comment by Stutternov** [comment]
> Seeing as Rangers somehow kept their R91s/Snipers/10mm smgs. It is a bit unfair that the Explorers are more or less given horrible guns. I'm not sure why this happened as I thought EVERYONES loadouts were being nerfed not one faction and frankly thats how it seems. They should atleast get a cowboy repeater or something? Hunting rifle isn't bad but it's underwhelming compared to comparble loadouts.

Hunting rifle is actually better than the Cowboy as it's doing 49.45 damage per bullet (Base 7.62 is 43 damage). Similarly, the SKS is a _better_ M1 Garand so.. I'm not sure why you'd upgrade in the first place from M1 Garand to SKS - let alone Hunting Rifle to SKS; as you are giving them a cracked M1 Garand.

Similarly, I was told by staff and LMs Explorers are not to be equal to rangers, thus why they were not even put up as whitelisted roles. They're 'legion unique' as Veterans are supposed to be equal to Rangers. (I'd actually say Explorers are more like Civi Rangers if anything at all.)

**Comment by BadAtThisGame302** [comment]
Yeah I doubt them not being given an SKS was accidental, the SKS is a very good round start rifle that nobody shouldn't have. So this "bug fix" is not it.

**Comment by RicktenStone** [comment]
Regardless of whether they mirror rangers or not, they mechanically are the only "snipers" the legion has, so it is kind of unfair to give them crappy hunting carbines when rangers have roundstart dks snipers and assault guns. Even if they don't mirror rangers, a faction should have better long range guns than that and sks is fine in that regard since all it is is a slightly better garand is a good equivilant to the dks sniper the rangers have that have their own advantages.

**Comment by AllCorruptingWyrm** [comment]
I'm not giving the melee faction a viable ballistic (anymore) so i'm closing this.

**Pull request closed without merging**
