### PR TITLE
Cape Removal

### PR DESCRIPTION
**Pull request by Stutternov**
## About The Pull Request
The Brotherhood cape sprite isn't great, the capes themselves make you just a bigger target, and make no lore-sense to have.

Asked to also remove NCr and Legion capes anyway by both NCR/Legion LMs, might as well axe the capes BOS hates too.

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog
:cl:
removes: removes all capes from spawning.
/:cl:

### CODE REVIEW

**Comment by AllCorruptingWyrm** [comment]
https://www.youtube.com/watch?v=WWaLxFIVX1s&ab_channel=animorphy

**Comment by BadAtThisGame302** [comment]
> the capes themselves make you just a bigger target

So the extra couple pixels erm... make the enemy click you easier so... we should remove other fluff items that do that as well.

**Comment by Zero-Percent-Angel** [comment]
To be fair, we could just have it so that if people don't want to wear them, they don't have to

**Comment by Serxule** [comment]
capes are already fully optional to wear, and more often than not are used as trophies as there arent restrictions unlike most faction armor, this doesnt make any sense at all

**Comment by Stutternov** [comment]
> capes are already fully optional to wear, and more often than not are used as trophies as there arent restrictions unlike most faction armor, this doesnt make any sense at all

They are not for Brotherhood and this is being amended in a sperate PR; if they are option they can be relegated to loadouts.

As for NCR and Legion, their LMs directly asked for all capes for those two factions to be removed.

**Comment by Stutternov** [comment]
Nevermind as I got told "NOOO WE NEED CAPES TO IDENTIFY BROTHERHOOD!!" so I will have to leave it. I've instead ported Atom Bomb's capes that are MUCH smaller in size. So, whatever. There. BOS capes have stayed.

Legion and Ranger capes are still removed as per request of NCR/Legion LMs.

**Comment by BigBigga** [comment]
LM moment

**Pull request merged**
