### PR TITLE
Ballistics Rebalance

### PR DESCRIPTION
**Pull request by maaacha**
## About The Pull Request
With the help of Daemon, the thunderdome, and plenty of cope analysis, I am happy to bring you a pretty heavy nerf/fix to a lot of the problems currently plaguing the ballistics weapons. Some weapons had the incorrect ammo typings, others had inexplicable damage bonuses, etc. A full list of changes is in the changelog.

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
balance: Cowboy Repeater: Bonus damage modifier removed (41 -> 36)
balance: .357 Revolver: Fire rate brought in line with similar revolvers
balance: 50 MG: Fixed ammunition type error. 50MG is now surplus instead of match and improvised is now handloaded instead of surplus. Effectively nerfs AMR damage (98 -> 75). Increased range on AMR scope from 13 tiles to 18 tiles to compensate.
balance: Minigun - Increased recoil, brought in line with other 5mm automatic firearms. Negative damage modifier applied (30 -> 19.5)
balance: Service Rifle - Fire rate decreased, brought in line with similar low tier semi automatic rifles.
balance: Thompson SMG - Decreased fire rate, brought in line with similar mid tier SMGs
balance: Sniper Rifle - Lowered damage bonus from tier 4 to tier 3 (60.75 -> 56.25). Lowered scope range from 2x to 1.5x, Increased recoil to match similar high calibre long range firearms.
balance: 14mm -- Lowered base damage (50 -> 43) 
balance: Police revolver fire rate lowered from faster to fast.

/:cl:

### CODE REVIEW

**Comment by AllCorruptingWyrm** [comment]
I really like a number of changes involved in this pr; The weapons on this server and TTK are insane. Only thing I can recommend right now is to leave comment notes about balance for future servers.

**Comment by Weaselburg** [comment]
i am wondering why you moved AMR to 75 instead of back down to 60 (where it was before CB code hit it)

**Comment by SingingSpock** [comment]
You should really use Gitkraken or a similar program to squash this PR. Currently it incorporates a bunch of commits from other PRs

**Comment by maaacha** [comment]
> i am wondering why you moved AMR to 75 instead of back down to 60 (where it was before CB code hit it)

This is where it is supposed to be according to the current code. A mistype had the surplus ammunition typed as match. Lowering it to 60 kind of invalidates the bolt action + high recoil effect and just makes it a shittier sniper rifle. It's meant to be rare and good -- just not two shot good.

**Comment by maaacha** [comment]
OK I fucked up let me redo this real quick XD

**Pull request closed without merging**
