### PR TITLE
Blythe Bugfixes and other changes

### PR DESCRIPTION
**Pull request by Sunlitty**
## About The Pull Request
This aims to fix some day 1 unfixed issues as well as add some extra exploration and value for players. Most notably, fixes the NCR farm area, removes the MP quarters, adds an underground labour station, adds an armory and detectives office to the town law, and adds some wasteland buildings.

## Changelog
:cl:
add: 
-Extra ghoul to bookstore downstairs
-Cafe and butcher's east of NCR
-Underground armory to town sherriff's
-Upstairs detective's office to town
-An underground penal colony farm thing for NCR captured prisoners
-A farmhouse ruin north of the Legion's camp
-More ghouls to the small gunshop in the south

del: 
-Killed the second house east of NCR
-NCR MP stations deleted (rip)
-Stairs to nowhere in the western school
-Ladder to nowhere in Legion camp
-Deleted the dumb non-functional NCR ss13 security autolathe

tweak:
-Moved sheriff and deputy spawns, added a small office area
-Replaced NCR MP chambers with an interrogation room
-MAJOR NCR NERF: Replaced NCR door on the brig. Lock your doors!
-Adjusted areas to the south of the map
-MAJOR NCR NERF: Removed most of the interior NCR doors in the ranger outpost
-Replaced deleted LO's office with the NCR workshop
-Replaced the door on the MO's office since I didn't have the heart to delete the office entirely. Added cobwebs for RP.
-Replaced the tiki torches from the officer's quarters underground. This area sucks still and half the people it was made for do not exist.

fix: 
-Added NCR farm to the NCR powernet.
-Made NCR farm an interior space
-Restored bugged upstairs to the bookstore
-Removed road corners which did not line up
-Changed some road tiles to not be edges in the middle of the road
-Replaced some lazily duplicated car ruins
-Removed a sand edge from the middle of a road
-Removed left behind fences near NCR base
-Windows in town clinic which opened onto a wall are gone

/:cl:

### CODE REVIEW

**Comment by Sunlitty** [comment]
Here's mad pics

[https://media.discordapp.net/attachments/1044717389058674690/1125113921762754671/Surface.png?width=845&height=676](url) (Surface)

[https://media.discordapp.net/attachments/1044717389058674690/1125113923134304256/Underground.png?width=845&height=676](url) (Underground)

[https://media.discordapp.net/attachments/1044717389058674690/1125113924086403162/Upper.png?width=845&height=676](url) (Above)

**Comment by Teragenic** [comment]
In issue of fairness. Remove Legion lock-doors too. Also, the MP stations should stay? They were used until someone commented out the MP helmets for ???

Farm should not be interior, doesn't make sense for a FARM. We already had a chat and a discussion on why we made the Ranger doors ID locked, talk to Tzula who made them ID locked in the first place.

Shouldn't it be a tweak instead of a del? If you replaced the house with a cafe and butchery...

Also, this doesn't include the checks if this compiles, if you've tested it on your own server. etc.

**Comment by Sunlitty** [comment]
> In issue of fairness. Remove Legion lock-doors too.
The Legion is pretty consistent with their locked gates. The exterior doors, as well as main doors to buildings. They don't have locked doors inside houses. You'll only ever need to break down two doors total to reach the inside of any one building. See below.

>We already had a chat and a discussion on why we made the Ranger doors ID locked, talk to Tzula who made them ID locked in the first place.
I do wanna explain what's up here. I've attached pics of what's going on there in detail.
image
image

The amount of locked NCR doors was INSANE. Right down to the kitchen and even the TOILET in the ranger outpost.

Examples:
IN RED are doors that were NCR reinforced but are now normal, blue are ones that were left alone.

To go through the front door and end up in the courtyard, you have to go through (or around if you're lucky) a WHOPPING 7 NCR REINFORCED DOORS. That is INSANE considering those are mostly intended for use as exterior doors. I feel like I have still been quite generous in keeping the doors I have.

I'll see about getting onto Tzuzzy still. 

>Also, the MP stations should stay? They were used until someone commented out the MP helmets for ???
MP has been deleted from the game. It sucks, but there you go. Makes no sense to have bunks and gear ready for nobody. I have seen the space used for RP with prisoners, so it made sense to have it be turned into a one-on-one interrogation room to give NCR something to do with their prisoners. There's also the cool underground work camp thing.


> Farm should not be interior, doesn't make sense for a FARM.
The NCR has two areas, an NCR interior with power, and an NCR exterior without. Since day 1 players have tried to farm at the NCR and been unable to as the area has no power, thus no machines or electric light. The area, upstairs on a building, is closer in spirit to a greenhouse anyway. A QOL **and** bugfix at the price of envisioning the area as a greenhouse.

> Shouldn't it be a tweak instead of a del? If you replaced the house with a cafe and butchery...
Old building gone entirely, new ones in the area near-ish where it was. A deletion and two new additions.
image

> Also, this doesn't include the checks if this compiles, if you've tested it on your own server. etc.
Yeah valid I'll sort that out today.

Cheers!

**Comment by AllCorruptingWyrm** [comment]
i'm actually okay with these changes personally and I overdid it on the doors so my bad, it was the launch and I was trying to get everything fixable.

**Pull request merged**
