### PR TITLE
PA Restoration Changes

### PR DESCRIPTION
**Pull request by DovaKitty**
## About The Pull Request
Here is a list of the things that this PR does:

-Adding a new item: Pristine circuits. They spawn in the advanced crafting spawners already in the map, and should not have any static spawns. Do not add static spawns of this item in the future.
-Pristine circuits are now required to make the PA servo kits
-PA servo kit recipe is duplicated, one for 80 repair and one for 80 science
-Legion can make their own salvaged PA from other SPA, with new sprites for both T45 and T51. They trade off one tier of armor for a tier faster in speed.
-Paladin-slayer sprite has been changed to fit the new theme, and its helmet is finally technically SPA
-Legion can no longer wear actual PA. It is a lorebreak. Call me post-fun.
-NCR SPA can now be made by every NCR slot instead of just a couple (don't see a reason to keep this around anymore)
-Total removal of T45b. It became irrelevant after the new changes to SPA and the introduction of T45d salvaged.

These changes should make PA restoration more stable mechanically, and makes it rely on random loot that you cannot metarush. You will need to find both SPA and the circuits, which will likely be in different dungeons. I tested everything I could on a localhost.

demo
## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl: Dova
add: New item to advanced crafting lootpool: pristine circuits
change: pristine circuits are now required to make PA servo kits
change: PA servo kits can now also be made with 80 Science instead of 80 Repair
add: Legion has three new sprites of SPA. One to replace the current Paladin-Slayer armor, and two more to convert from T45 and T51 SPA
change: Legion can't wear actual PA anymore. It's a lorebreak. This is now a post-fun server.
change: All NCR slots can now make NCR SPA
removal: T45b should now be wiped from the game's code
/:cl:

### CODE REVIEW

**Comment by VEN0M5** [comment]
The current raider SPA can already be used with the servo kits, in fact I restored it once.... I think all suits of SPA already could be restored due to inheritance

**Comment by DovaKitty** [comment]
> The current raider SPA can already be used with the servo kits, in fact I restored it once.... I think all suits of SPA already could be restored due to inheritance

Thanks for letting me know. Should be good now.

**Comment by DovaKitty** [comment]
Waiting on someone who has Tipton access to remove the last trace of T45b scum before I publish.

**Comment by DovaKitty** [comment]
> Waiting on someone who has Tipton access to remove the last trace of T45b scum before I publish.

Got it removed from Tipton. PR should be safe to merge.

**Pull request merged**
