### PR TITLE
Ports Fatman Launcher

### PR DESCRIPTION
**Pull request by HanSolo1519**
## About The Pull Request
Title, [ported from upstream](https://github.com/ARF-SS13/coyote-bayou/pull/1578)

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by HanSolo1519** [comment]
still needs playtesting but it's currently 5:36 am, lol, lmao.
Good enough to merge, icons might be fucked, who knows.

**Comment by Zero-Percent-Angel** [comment]
@HanSolo1519  Some conflicts on this now, when you get a chance can you take a look?

**Comment by TheEternalFlame** [comment]
Does this add it to the loot tables? If So then I would like that disabled.

**Comment by HanSolo1519** [comment]
> Does this add it to the loot tables? If So then I would like that disabled.

This does not, and it shouldn't. It's intentionally not intended for balance. Maybe as a 0.1% chance in a unique spawned as a hehe hoo haw, but that's not for this pr. it's big, it can 1 hit kill in atleast a 7x7 zone, if not more.

This just adds the weapon, unused. Cornercube reported that the magazine is bugged so I still gotta fix that.

**Pull request closed without merging**
