### PR TITLE
Salvaged & PA Nerf

### PR DESCRIPTION
**Pull request by Stutternov**
## About The Pull Request
As requested by Myrios, nerfed values of PA to only 80 effective health with 20 extra laser protection (so 100 laser protection) from 125 and 135 respectively. Also reduced salvaged PA effective health from 90 to 80 with 10 extra laser protection, reducing both values by 10 basically.

Tl:dr - Salvaged and regular PA have 90 protection and extra laser protection (90 for Salvaged, 100 for PA). This should nerf the effective health values harder to make mobs and damages easier to balance. This also makes salvaged PA desirable instead of always being inferior to PA. (Kinda is but can’t be ioned at least; so it just doesn’t get +10 laser, gun recoil reduction, or the faster speed but still has the same protection.)

Similarly I rebalanced PA types.
- T45D only has 90 laser instead of 100, because in lore it’s not as protective.
- T51B has received a mild nerf to it’s large protection
- Excavator had to be tweaked to not be total ass. It’s kinda worse than salvaged PA now but has bonus melee protection and faster movement.
- PA EMP severity is reduced from 4 in heavy to 2 and 2 in light to 1. Why? The cell dying also slows you down besides the EMP, so I feel this is fair considering the extreme armor reduction value wise to be still desirable over most salvaged if an option is possible. Similarly the range of EMPs is somewhat strange so you can barely be in the blast and it will empty most cells anyway.

Also fixed T-45 names as T-45b is not canon nor do we really need to specify between them as they are basically the exact same sprite.
## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog
:cl:
balance: Adjusts PA and salvaged PA values.
balance: Lowers EMP caused severity slowdown as the slowdown stacks with the cell being dead.
tweak: no more non-canon names
/:cl:

### CODE REVIEW

**Comment by Stutternov** [comment]
as an ncr legion vault town main i hate the brotherhood!!!!!

**Comment by Myrios** [comment]
A solid and necessary step in pulling back the powercreep regarding PA.
I will slay in single combat any man whosoever naysays this brave freedom fighter.

**Comment by VEN0M5** [comment]
Was reducing PA EMP slowdown intended?

**Comment by Stutternov** [comment]
> Was reducing PA EMP slowdown intended?

Yes, the slowdown is done via empty effect plus cell power. It stacks is why I lowered it as the slowdown by EMP is done based on severity and cells are almost always fried, regardless of cell type nearly, even in low severity. I feel it’s fair given the severe armor reduction.

**Comment by Serxule** [comment]
i feel like having two identical sets of PA is going to be a pain, why not just remove functioning t45b since it isnt even supposed to exist

**Comment by Stutternov** [comment]
> i feel like having two identical sets of PA is going to be a pain, why not just remove functioning t45b since it isnt even supposed to exist

I don’t think it’s in rotation besides raider armors which use it’s subpath; I didn’t want to have to touch spawners to repath all salvaged raider armors since I know other people are rn.

**Comment by Zero-Percent-Angel** [comment]
While I do think some of the number slashes seem a bit harsh, but given that PA gives other benefits as well as armor, I think we can let this through and take another look at how it's performing in live after a few rounds.

**Pull request merged**
