### PR TITLE
Legion rework season 2

### PR DESCRIPTION
**Pull request by Metriusthehot**
## About The Pull Request
Read about it right here: https://docs.google.com/document/d/1RnX7Mm04boBebJUeiJS8thrPxRe-3j160_I4s_11hDU/edit?usp=sharing
Pictures and everything im so cool 
POWER WORKS NOTHING NEEDS FIXED WE READY FOR MEEERGE

## Pre-Merge Checklist
- [✓] You tested this on a local server.
- [I still dont know what this means] This code did not runtime during testing.
- [✓] You documented all of your changes.

## Changelog
:cl:
add: A whole new legion camp to replace the old one
add: Some fixes to the roads
del: Old legion camp because it sucked
/:cl:

### CODE REVIEW

**Comment by AsterixCodix** [comment]
I'll be completely honest here: this is unnecessary.

The current Legion base on Tipton is less than a month old. It needs adjusting slightly, yes, but outright replacing it is just overkill. You don't break out a flamethrower to deal with 1 spider, you know?

The current Legion base is an old casino. This... I can't tell what this is meant to be. The format of the doc doesn't help with that either but, that might be a mobile issue. Is it more practical? Maybe. But at the cost of the flavour and style of their current base on Tipton being tossed out. It feels so much smaller and muddled, like, there's just a random diner thrown into their base... Why? It feels like there wasn't much thought put into this beyond "Current one is shit, Ima do this shit myself".

**Comment by Metriusthehot** [comment]
I had no clue about the timeline of this one's existence since it's existed as long as I have been back but a lot of people dont understand the theme and just hate the base as is. Most active players (as I ask in ooc) said they didnt even know it was a casino they thought it was a bus station. Theres also already the khan casino down the road. I really hate the current base as many others do and it goes unused for the most part. This one is like the legion fenced off a plot of land and conquered all buildings inside making a congregation within those bounds, there are two buildings that would have existed prewar (the concrete) and one big one that they clearly refurbished from remains of old in the middle, all of which have their uses. 
I wanted to talk with the legion lm to get more lore into the new one but they refused to accept my request and I didn't want to add too much without their opinion on it so I went more for practical than story rich with things that still made sense in the setting.

**Comment by Metriusthehot** [comment]
It also looks a lot smaller overall but the parts of the base actually used in the current one are tiny and this one is all usable while the same amount of space.

**Comment by Metriusthehot** [comment]
fuck tiberius and flavius, yall should merge

**Pull request closed without merging**
