### PR TITLE
Next Dev Iteration

### PR DESCRIPTION
**Pull request by Zero-Percent-Angel**
Slight buff to healing powder, should metabolise faster now, and apply quicker too.

New admin verb, which should help admins integrate skills into events!

Run and Gun! Changed the 'Recoil buildup' when moving to a flat aim penalty (Determined by skill) for moving, which disappears once you stand still on your next life tick.

### CODE REVIEW

**Comment by VEN0M5** [comment]
Metabolise faster means it runs out faster, not heals faster if that is what you were intending... So a nerf to total health healed

**Comment by BadAtThisGame302** [comment]
Why did you change 101 files for these?

>  Slight buff to healing powder, should metabolise faster now, and apply quicker too.
New admin verb, which should help admins integrate skills into events!

**Comment by Zero-Percent-Angel** [comment]
> Why did you change 101 files for these?
> 
> > Slight buff to healing powder, should metabolise faster now, and apply quicker too.
> > New admin verb, which should help admins integrate skills into events!

That log is my changes, but it also includes all the other PRs that are in flight and being merged into Dev too :)

**Comment by Zero-Percent-Angel** [comment]
> Metabolise faster means it runs out faster, not heals faster if that is what you were intending... So a nerf to total health healed

image
Hopefully this image will arrest your concerns

**Comment by BadAtThisGame302** [comment]
> > Why did you change 101 files for these?
> > > Slight buff to healing powder, should metabolise faster now, and apply quicker too.
> > > New admin verb, which should help admins integrate skills into events!
> 
> That log is my changes, but it also includes all the other PRs that are in flight and being merged into Dev too :)

So any merged PR has to be inserted into another PR so that it can finally get on the server?

**Comment by Zero-Percent-Angel** [comment]
> > > Why did you change 101 files for these?
> > > > Slight buff to healing powder, should metabolise faster now, and apply quicker too.
> > > > New admin verb, which should help admins integrate skills into events!
> > 
> > 
> > That log is my changes, but it also includes all the other PRs that are in flight and being merged into Dev too :)
> 
> So any merged PR has to be inserted into another PR and that new PR has to also be merged so that it can finally get on the server?

Yes, It's how I test things. I've caught a few bugs on the stuff in here. It's mostly for quality control. In most projects it is useful to have a separate dev branch to the 'live code' it's not exactly a rare thing in software engineering!

**Comment by YosemiteYam** [comment]
Be careful about the "metabolizing faster" for healing powder, I think the same thing was done for bitter drink and now it heals less overall while going through your system faster, and effectively nerfed it. This will do the same thing if healing isn't adjusted as well. Honestly just remove the delays for application for powders and bitter right now instead of just reducing them, tribal meds being fixed compared to instant heal stimpacks has been asked for for a while now.

**Pull request merged**
