### PR TITLE
Long overdue laser weapon and armor rebalance

### PR DESCRIPTION
**Pull request by CUST-0M**
## About The Pull Request
Lasers are pretty much better than any other firearm in this game, which is saying a lot since guns already do lots of damage. The reason for this is because of three things:
1) Laser weapons are hitscan, yet do as much damage as ballistics
2) Energy weapon attachments are capable of increasing weapon damage
3) There are tonnes negative modifiers to armors for laser damage

All three of these problems are solved with this PR. The higher end laser weapons that were considered less effective than lower tier lasers were nerfed to a lesser degree than the common ones. Armor that isn't specifically made for bullet resistance only will on average have one or two levels less of laser resist than it does bullet resist or have none at all.

Will this make laser weapons useless?
Nope, they're still hitscan so far more of your shots will land than with ballistics.

Why lower the laser resist debuffs on armor?
Lasers are not armor penetrating guns in fallout nor should they be like that here. That would be plasma weaponry, which is untouched. Armor is still worse when dealing with lasers despite of this, mainly in an attempt to reduce disagreement.

Why the attachment nerf?
Because ballistics attachments, even the rare ones are far worse than energy weapon attachments.

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
tweak: laser weapons do less damage across the board, nerfs are based on the weapon's rarity.
tweak: energy weapon attachments do not grant extra damage or AP and have been changed to grant different buffs
tweak: penalty to laser weapons on armors has been decreased in general

### CODE REVIEW

**Comment by AllCorruptingWyrm** [comment]
No. I disagree with these changes.

**Comment by az492** [comment]
a good change to laser weapons for once as a high damage + high fire rate + hit scan weapon is always going to outclass everything else, power creep has left them at the position they are today and changes like this are welcome to see.

**Comment by panzerr1944** [comment]
Energy attachments and weapons got hit by a nerf and rebalance respectively already. I don't see the need for this PR, especially when all it's doing is over-nerfing the majority of weapons.

**Comment by AsterixCodix** [comment]
This feels more like a salt PR, than anything else. This will make the weapons borderline unusable.

**Comment by FantasticFwoosh** [comment]
Please consider the following.

- Major factions lost to a BOS co-ordinated force, actually just the once in the last couple of rounds, with combined mass fire to especially make up for the knowledge that ballistics outscale energy weapons faster in variation and quality. The same will happen again even if the guns are weaker, because that's the prevalent strategy of hitscans versus a 1v1.

- _Hitscan does not work(*)_ if you are currently concealed by smoke, by depriving anything to click on.
- _(*)Most hitscans psuedo-projectile fly until they reach a target_,  if you lie down, in which you still have access to use of your weapon twohanded you can severely recompense shooting back with mass fire.

🚩: IC preparation skill issue, this is a little bit of a gratuitous grudgenerf in my opinion.

**Comment by Weaselburg** [comment]
This very much seems like a cope PR given that laser weapons were nerfed/rebalanced in the last few days. Maybe improve thy skill.

**Comment by UntoldTactics** [comment]
This PR does nothing to address laser weapon fire rates despite heavily modifying their damage and the damage others get from lasers. As above, there was a recent PR that rebalanced laser weapons.

The fact you want to do stuff along the lines of making the AER9 have 18 damage, whilst retaining the fire rate it previously had is really not sound.

**Comment by AllCorruptingWyrm** [comment]
This is a bad pr and made out of bad faith. This was one of the best and worse decisions frok made regarding balance.

**Comment by DaemonTinadel** [comment]
This PR does things correctly. Lasers are op. You can argue they aren't but again when your wearing armor that receives a negative /no positive in laser prot. You just die. A laser bus
real
 which may be hard to get one taps you in Vet Decan armor, If I had a instant kill melee it'd make people complain just as much. It's not fair that one side is more or less weighted negatively against the other. That being said these changes are a bit too much for the moment, can be fixed better by giving legion laser prot/increasing fire rate across the board for lasers  and tuning down damage.

**Comment by CUST-0M** [comment]
> Please consider the following.
> 
>     * Major factions lost to a BOS co-ordinated force, actually just the once in the last couple of rounds, with combined mass fire to especially make up for the knowledge that ballistics outscale energy weapons faster in variation and quality. The same will happen again even if the guns are weaker, because that's the prevalent strategy of hitscans versus a 1v1.
> 
>     * _Hitscan does not work(*)_ if you are currently concealed by smoke, by depriving anything to click on.
> 
>     * _(*)Most hitscans psuedo-projectile fly until they reach a target_,  if you lie down, in which you still have access to use of your weapon twohanded you can severely recompense shooting back with mass fire.
> 
> 
> 🚩: IC preparation skill issue, this is a little bit of a gratuitous grudgenerf in my opinion.

This isn't a BoS specific nerf, but I'll talk about it since it's the only one that isn't someone going "Nuh uh!! They aren't OP!!".

Major factions lost to a BoS coordinated force because they spawn with the best armor in the game and the best weapons in the game, laser weapons. Having an extra two or three bodies cannot make up for this disparity.

I have tested laser weapons, both using them and having to fight them. When using them, I experience a sudden and clear increase in my character's combat effectiveness. This is because they are better than the ballistics I usually use and not because I am somehow "more skilled" with laser weapons. Everyone is.

Having to use smoke against a weapon is a clear indicator that it is too strong. "If you want to beat someone using this weapon, use smoke grenades so they drop it because you aren't winning if they have it in their hands."

To give you an example on how massively bloated laser damage is, the laserbuss fires eight beams simultaneously which each do 25 damage. That is 200 total damage, meaning if you have 100 HP and are wearing some of the best anti-laser armor in the game, you will still get one shot by a laserbuss with no weapon mods. And it's hitscan.

Most people making the claim that laser weapons in their current state are not vastly more effective than projectile weapons are those who use these weapons and find it more comfortable to believe that the reason they are effective in combat is due to their own skill and not the superiority of the weapon type they use over others.

**Comment by Stutternov** [comment]
With this change you would never, ever, use a laser weapon.

I do agree with reworking the armors to lower laser protection even tho that was my doing since, yes, it turns out it needs to be adjusted and that is fully 100% understandable.

I can even understand the 'no more bonus AP' to lasers in a manner.

But - this PR makes laser weapons **fully** useless. I would use a 10mm pistol sooner than even a laser rifle in this case, as ballistics do:
- Bleed damage
- Stamina damage
- Wounds
- Some have super-effective damage (Gauss as an example)
- Can be modified better than laser weapons can be
- Automatic

Atop of other reasons. This would simply mean not a soul would ever take an energy weapon - which, honestly, even as a BOS player who doesn't like energy weapons ICly or OOCly - even _I_ can see this would mean: "Yeah, why tf would I even use this in an emergency over a ballistic pistol even?"

Only input I have I gave to the other energy weapon PR where I highlighted they needed to either add recoil to laser weapons or reduce the damage. Which - same here, but the damage reduction is SO FAR to the point of absolute uselessness.

**Comment by FlickTee** [comment]
Lol what even is this? AER9 30 to 18 damage, wattz 50 to **23**, 40% or so less damage on every weapon on top of removing energy weapon vuln on armors? This is one ridiculous PR, energy weapons aren't _THAT_ good.

**Comment by Weaselburg** [comment]
> > Please consider the following.
> > ```
> > * Major factions lost to a BOS co-ordinated force, actually just the once in the last couple of rounds, with combined mass fire to especially make up for the knowledge that ballistics outscale energy weapons faster in variation and quality. The same will happen again even if the guns are weaker, because that's the prevalent strategy of hitscans versus a 1v1.
> > 
> > * _Hitscan does not work(*)_ if you are currently concealed by smoke, by depriving anything to click on.
> > 
> > * _(*)Most hitscans psuedo-projectile fly until they reach a target_,  if you lie down, in which you still have access to use of your weapon twohanded you can severely recompense shooting back with mass fire.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 🚩: IC preparation skill issue, this is a little bit of a gratuitous grudgenerf in my opinion.
> 
> This isn't a BoS specific nerf, but I'll talk about it since it's the only one that isn't someone going "Nuh uh!! They aren't OP!!".
> 
> Major factions lost to a BoS coordinated force because they spawn with the best armor in the game and the best weapons in the game, laser weapons. Having an extra two or three bodies cannot make up for this disparity.
> 
> I have tested laser weapons, both using them and having to fight them. When using them, I experience a sudden and clear increase in my character's combat effectiveness. This is because they are better than the ballistics I usually use and not because I am somehow "more skilled" with laser weapons. Everyone is.
> 
> Having to use smoke against a weapon is a clear indicator that it is too strong. "If you want to beat someone using this weapon, use smoke grenades so they drop it because you aren't winning if they have it in their hands."
> 
> To give you an example on how massively bloated laser damage is, the laserbuss fires eight beams simultaneously which each do 25 damage. That is 200 total damage, meaning if you have 100 HP and are wearing some of the best anti-laser armor in the game, you will still get one shot by a laserbuss with no weapon mods. And it's hitscan.
> 
> Most people making the claim that laser weapons in their current state are not vastly more effective than projectile weapons are those who use these weapons and find it more comfortable to believe that the reason they are effective in combat is due to their own skill and not the superiority of the weapon type they use over others.

i'm not here to argue since i already said my piece but the laserbuss does not spawn anymore.

**Pull request closed without merging**
