### PR TITLE
Outlaw tribal loadouts

### PR DESCRIPTION
**Pull request by TheEternalFlame**
## About The Pull Request
 Moves White-Legs and Eighties loadouts into the outlaw loadouts and increased the number of Outlaw slots from 6 to 10.

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by X404ErrorX** [comment]
As a frequent tribal player I don't like the change, I know it doesn't really affect anything but the white legs are cyon tribals and they should be in the same role as the sorrows and dead horses, about the 80s I don't know much about the lore but It is true that they look more like civilized than tribal raiders. One more thing, if possible, would you mind adding bodypaint to tribal loadouts that don't have this item?

**Comment by Cleverslim** [comment]
tribal roles get tribal language comprehension as a default. This will effectively remove white legs tribal language unless they take the quirk to understand it.

**Comment by Cleverslim** [comment]
Also would remove all the tribal recipes from white legs

**Comment by Zero-Percent-Angel** [comment]
> As a frequent tribal player I don't like the change, I know it doesn't really affect anything but the white legs are cyon tribals and they should be in the same role as the sorrows and dead horses, about the 80s I don't know much about the lore but It is true that they look more like civilized than tribal raiders. One more thing, if possible, would you mind adding bodypaint to tribal loadouts that don't have this item?

The issues isn't lore related it's playstyle related, people play them roles as antagonists. We generally have higher expectations for antagonists, so they fit better under the role that has those regulations rather than putting tribals on the outlaw whitelist.

**Comment by X404ErrorX** [comment]
Uh, so this whole change is just to whitelist a role literally played by 4 people, funny.

**Comment by Cleverslim** [comment]
> > As a frequent tribal player I don't like the change, I know it doesn't really affect anything but the white legs are cyon tribals and they should be in the same role as the sorrows and dead horses, about the 80s I don't know much about the lore but It is true that they look more like civilized than tribal raiders. One more thing, if possible, would you mind adding bodypaint to tribal loadouts that don't have this item?
> 
> The issue isn't lore related it's playstyle related, people play them roles as antagonists. We generally have higher expectations for antagonists, so they fit better under the role that has those regulations rather than putting tribals on the outlaw whitelist.

if its supposed to be a whitelist role why even have a limit on it then, and this still doesnt address all the issues it brings up with whitelegs not having access, to tribal language comprehension, and tribal crafting and the other things tied to being the tribal role that you will no longer have access to.

**Comment by FantasticFwoosh** [comment]
It'd be easier to just make a new tribal outlaw/guide role, since most noted tribals have a clear affiliation to a faction. Also, Bonedancers are a OWB raider tribe, with a quite heavy emphasis on a negative theme, but they aren't quite as played out as the others like whitelegs, just due to the lack of attention given to them, to which they could still be guides for the NCR or just join outlaw counterparts via the gang mechanic. Same can be said for Rustwalkers, which have a synergy with tech heavy factions.

**Comment by RicktenStone** [comment]
There's a pretty limited amount of outlaw slots, even with the bump. Why arbitrarily put white legs behind an outlaw slot..when they aren't outlaws? Its up to peoples prerogative on how they want to play their tribal, its entirely legitimate to play a white leg either as one that is antagonistic to certain factions or as more peaceful, since their lore supports it. Seems like a bad reason to put them behind a very limited outlaw slot especially in high pop where they get gobbled up fast. It also forces people who want to go white leg to act like an outlaw in order to justify them taking a limited slot, even if they want to play it more passive

**Pull request merged**
