### PR TITLE
Tipton Map

### PR DESCRIPTION
**Pull request by AllCorruptingWyrm**
## About The Pull Request
https://cdn.discordapp.com/attachments/1120747252353355847/1120747419135647744/2023-06-20_18.08.19.png
https://cdn.discordapp.com/attachments/1120747252353355847/1120747420075184219/2023-06-20_18.08.10.png
https://cdn.discordapp.com/attachments/1120747252353355847/1120747420909838446/2023-06-20_18.08.04.png
https://cdn.discordapp.com/attachments/1120747252353355847/1120747422625321012/2023-06-20_18.07.55.png

 This PR adds Tipton and the JSON file for Tipton. Images will be included in the comments section.

## Pre-Merge Checklist
- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog, 
:cl: Myrios, TheEternalFlame, AsterixCodix, Tzula/Wyrm, Spockye.
add: Tipton, the Map.
/:cl:

### CODE REVIEW

**Comment by AllCorruptingWyrm** [comment]
credits to Myrios and Tef for making the map, I'm only just posting it for Tef.

**Comment by K4rlox** [comment]
provide picture

**Comment by AllCorruptingWyrm** [comment]
image
image
image
image

**Review by spockye — CHANGES_REQUESTED** [review]
First off use the screenshot function for yer images
---
image


And for the errors

image

tags like these are illegal. Remove them
Read the error log to see where and what they are


image

Var editing zones is illegal. Make proper subtypes

**Comment by spockye** [comment]
SURFACE ERRORS
---
image

missplaced floors

image

missplaced floors

image

missplaced floors

image

missplaced zones (shouldnt tcomms be tcomms?)

image

missplaced zones (city??)

image

whats going on with the sofa? also the two autodocs look like they're a really tall tower, funny but painful to look at


image

give the detective a office 🥺 

UNDERGROUND ERRORS
---

image

missplaced floors

image

missing floors?


SKY ERRORS
---

image

missplaced floors






It's 3 am and i crave the sweet release of unawakedness. i'll probably expand on the review tomorrow

**Comment by TheEternalFlame** [comment]
My existence is suffering.
I'll fix the issues in a bit.

**Comment by K4rlox** [comment]
> also the two autodocs look like they're a really tall tower, funny but painful to look at

the twin towers

**Comment by spockye** [comment]
no idea what's causing the final errors. could anyone try to explain it to me?

**Comment by spockye** [comment]
Im dumb, errors are on the skyz 

I should read

**Comment by BadAtThisGame302** [comment]
Can you install mapdiffbot and icondiffbot on the Git? So we don't have to post screenshots of icons/maps changing and could easily see the changes without annoying the author? Thanks.

**Comment by AllCorruptingWyrm** [comment]
ITS DONE
THE MAP WILL BE SET TO A DEFAULT
PLEASE PLEASE PLEASE BE ON STANDBY FOR THE ROUND WHEN THE MAP IS MERGED BECAUSE IT WILL BE AUTOMATICALLY PLAYED WHEN MERGED AND MOUNTED ON THE SERVER

thank you tef, myrios and spockeye!!!

**Comment by spockye** [comment]
spockEYE!????

**Comment by spockye** [comment]
image
the new ruined town

**Comment by spockye** [comment]
ready for TM

**Comment by Zero-Percent-Angel** [comment]
image
probably shouldn't have random trash in the Vault spawning arms... sends the wrong messages to the players.

**Comment by Zero-Percent-Angel** [comment]
Is this area supposed to have weather:
image

**Comment by AllCorruptingWyrm** [comment]
there are some bugs 

I need to fix this and update it. I advise reverting test merges for now.

**Comment by Zero-Percent-Angel** [comment]
I have to back this out from test merged while there is a conflict

**Comment by Zero-Percent-Angel** [comment]
We've got the other Tipton PR open now so... I am going to close this one

**Pull request closed without merging**
