### PR TITLE
G11 magazine size tweak

### PR DESCRIPTION
**Pull request by AllCorruptingWyrm**
## About The Pull Request
Needs testing. Adjusted the G11 magazines because they were kinda silly to be that large and be unable to be slotted onto a belt. Will comment when ready.

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog
:cl:
tweak: Magazine change
/:cl:

### CODE REVIEW

**Comment by Zero-Percent-Angel** [comment]
As an alternative, we could always make it so that belts can accept them no matter their size.

**Comment by UntoldTactics** [comment]
Note this issue plagues the P90 too. Goofy aah.

**Comment by UntoldTactics** [comment]
Note this issue plagues the P90 too. Goofy aah.

**Comment by AllCorruptingWyrm** [comment]
This can be merged, I'll do belt changes in another pr, I wanna atomize them a bit more.

**Pull request merged**
