### PR TITLE
Cuts BOS slots

### PR DESCRIPTION
**Pull request by Knightfall5**
## About The Pull Request
Reduces Brotherhood combat slots from 20 -> 14. Probably still not enough but we'll see, better to make small adjustments and correct later.

## Changelog
:cl:
balance: Cut BOS slots by 6
/:cl:

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
Just close this PR now before the Maintainer does (or if the BoSoids make GitHub accounts and downvote your PR) chud, no way in hell will your "radical" PR be merged... It's quite literally Joever

**Comment by Serxule** [comment]
scribes arent a combat role lol

**Comment by Knightfall5** [comment]
If a role is going into raids guns in hand and nothing is preventing them from doing this they are a combat role. If a role is so desired it's filled most of the time that is not 'unplayed'. The Brotherhood have far too many slots for a faction that was always balanced with "You get the best stuff but the least players". Round-start PA is 100% a power role.

**Comment by DovaKitty** [comment]
Only good idea here is removing a senior knight slot. I don't know why it was 2 to begin with. Everything else is BAD and you should feel BAD for pulling this.

**Comment by Serxule** [comment]
> If a role is going into raids guns in hand and nothing is preventing them from doing this they are a combat role. If a role is so desired it's filled most of the time that is not 'unplayed'. The Brotherhood have far too many slots for a faction that was always balanced with "You get the best stuff but the least players". Round-start PA is 100% a power role.

PA means nothing without a strong weapon or just plain skill, do you see how often paladins die? the loadouts paladins have is an r91, aer9, or supersledge and powerfist, that is not the gear power roles have, also, what i mean by "unplayed" is that it will almost always be the same people who are playing it, leaving nobody else to get to try it, so for the majority of people it will be unplayed for the. saying "if x can go into a raid with a gun its a combat role" is an utterly bullshit argument, scribes are not a combat role, off duties of any faction are not a combat role, townies arent a combat role, yet they can all go fight people with guns, that doesnt mean they're a fucking combat role

**Comment by Knightfall5** [comment]
If you are able to attend a raid and shoot at people without getting bwoinked you are a combat role, you contribute to the size of your faction's raiding party. Camp Followers are not a combat role, off duty are not a combat role, Scribes are a combat role because they attend raids and no one is stopping them from doing so.

**Comment by Zero-Percent-Angel** [comment]
Sorry this isn't the direction the LMs want to take the faction in for now.

**Pull request closed without merging**
