### PR TITLE
Energy Ammo Changes

### PR DESCRIPTION
**Pull request by DovaKitty**
## About The Pull Request
This PR adds weapon cell salvaging. You can get cell salvage from cars, broken machinery and destroyed turrets in different amounts. You can turn that salvage into weapon cells using a workbench. This PR also makes MFC and ultracite cells unchargable due to lore reasons. There should be enough ways to get them now. The following are ways to get the salvage:

Weld a car: Requires either 35 science and technophreak or 50 science. These two can stack to increase amounts.
Weld broken machinery: Requires 35 science or 50 science or 35 science and technophreak. These three can stack to increase odds.
Use a crowbar on a destroyed turret: Gets one or two without any skill requirements. If you have technophreak and 35 science, you have a chance to get more.

Hopefully this PR gives slots other than Scribe and Vault Scientist another reason to put points into Science, as it is somewhat of a dump skill.

Edit on 7/25/23: By request of the BoS/Vault LM Asterix, MFCs are no longer able to be printed by protolathes, for the same lore reasons.

Edit on 7/26/23: After talking with a lot of people about this, more changes are being made. No weapon cells are now able to be printed from the protolathe, and no weapon cells are able to be charged. Instead, three crafting recipes have been added to produce the three weapon cells, and the recycling recipes have been changed as well. The recycling recipes now require science based on the type of cell: 35 for ecells, 50 for ecps, 65 for mfcs. You are able to recycle two empty cells into one full one. The following are the needed materials to make each cell from scratch:

Energy Cell: two standard batteries (get these from an autolathe), 2 electronic parts, 3 cable coils at a workbench (35 Science)

Electron Charge Pack: 2 energy cells, 2 metal parts, 2 electronic parts, 3 cable coils at a workbench (50 Science)

Microfusion Cell: 2 energy cells, 2 high quality parts, 2 electronic parts, 3 cable coils at an advanced workbench (65 Science)

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl: Dova
-Adds the ability to salvage weapon cells, helped by the Science skill.
-Fallout weapon cells are no longer able to be charged.
-Removes the ability to print weapon cells using protolathes.
-Adds crafting recipes for the three main weapon cells, using the Science skill.
-Modifies the 2-1 weapon cell recharging recipes to use the Science skill.
/:cl:

### CODE REVIEW

**Comment by Teragenic** [comment]
You do know people need 50 science to make stims... So Scribes will most likely already have it. Also, BOTH roles allow for ammo printing via protolathe. I'd prefer maybe instead making it possible to make specific types of cells instead of random? If I'm reading this right.

**Comment by Serxule** [comment]
or just have it be lower than 50 since the majority of people will not have enough spare skill points if they're going to do combat

**Comment by DovaKitty** [comment]
> or just have it be lower than 50 since the majority of people will not have enough spare skill points if they're going to do combat

You don't need 50 to get the salvage. It just gets you more.

**Comment by Weaselburg** [comment]
I said it on the discord but I'll say it here for posterity.

Making energy cells non-printable/craftable does not add anything to the game. It just makes using energy weapons - which, in quite a few ways, are inferior to ballistics - more annoying. It adds another task for wasters/bos and makes it ESPECIALLY hard on wasters since the BoS run through tons of microfusion cells during combat ops and making them unchargable AND uncraftable just means they stockpile literally every MFC on the map, because if they DON'T they're FUCKED.

'Lore reasons' sucks ass given how bad this will affect gameplay. This will, in fact, actively discourage energy weapon usage and make ballistics even more of a king then it already is.

**Comment by DovaKitty** [comment]
Putting into draft because I'll be making some changes today

**Comment by Serxule** [comment]
why are ecps easier to get than mfcs when ecps are not only harder to get normally but are used for the rarer and stronger guns, compared to mfcs which are common and used for almost every laser gun??

**Comment by MichaelMaCleod007** [comment]
So unless BOS always has a competent Scribe who will keep them supplied in energy ammo for the week they will just be more militant and confiscating everything energy related from wasters. This will also become a serious issue if someone obtains a pulse rifle and essentially wipes out what will now be preciously rare energy ammo cells. I mean as BOS I mainly use ballistics anyway so this won't effect me much, but I am concerned this will result in more IC issues with the rest of the wasteland.

**Pull request closed without merging**
