### PR TITLE
Legion faction combat armor icon fix

### PR DESCRIPTION
**Pull request by Osmos123**
## About The Pull Request

Attempts to match the icon/item state to the sprites in the dmi file.
I got tired of seeing the error symbols when converting combat armor into legion faction.
## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
fix: attempt at matching the item/icon state to the sprites for faction combat armor.
/:cl:

### CODE REVIEW

**Comment by Teragenic** [comment]
Hey uh! Please make sure to check the sprites for the NCR, I thought the combat armor for the NCR icons worked fine and they looked fine.

**Comment by Teragenic** [comment]
Also the issue of this 
image
Atleast check it doesn't runtime

**Comment by Osmos123** [comment]
> Hey uh! Please make sure to check the sprites for the NCR, I thought the combat armor for the NCR icons worked fine and they looked fine.

Good point, just checked in game the ncr combat armor sprite is good. I looked more into it and the legion combat armor "icon" and "sprite" have different naming conventions.

image

image

image

They obviously look somewhat different, but however did the sprites did not include a duplicate icon.

**Comment by Osmos123** [comment]
> Also the issue of this image Atleast check it doesn't runtime

Checked in local server
before
image
after
image

**Comment by Osmos123** [comment]
image

now its using a different sprite set

image

**Comment by Osmos123** [comment]
It appears to work now
image
image
image

The only changes i made was the naming scheme of both icons
image

from before
image

**Comment by Serxule** [comment]
> image
> 
> now its using a different sprite set
> 
> image

that uh, you can literally do that using a colormate

**Pull request merged**
