### PR TITLE
RCW-14mm destruction

### PR DESCRIPTION
**Pull request by TheEternalFlame**
Lowers the RCW damage to 15 from 19 and replaced the Legion Assassin 14mm with a Breacher/Riot shotgun instead.

## About The Pull Request
 As they title says. From MP5 to Tommygun to Beacher. Along with updating and fixing the venator sniper rifle that was weaker than the normal sniper as it was marked with a lower damage tier than it was supposed to have.

Also adds a new loadout to the Legion assassin with a 10mm smg.

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by az492** [comment]
classic, trash admin trash PR. Nice job jannie.

**Comment by CUST-0M** [comment]
An MP fucking 5

**Comment by maaacha** [comment]
mp5 is way too dog for the one slot legion power role

**Comment by panzerr1944** [comment]
Just give them a zased riot shotgun or something if you dont want them to have the holy 14mm SMG. The MP5 will make the loadout useless compared to the sniper rifle. I have yet to see literally anyone use the MP5 non-ironically for anything but PVE.

**Comment by VEN0M5** [comment]
9mm is currently dogshit, MP5 just does 22 dmg. Give them a riot shotgun or at least some other smg. Well legion can get a 14mm most of the rounds anyway since on blythe that ghoul dungeon just north of thier camp can spawn it

**Comment by Serxule** [comment]
there's already a PR that changes the rcw bro, also yeah give a high tier role a mid/low tier weapon thats such a good idea

**Comment by TheEternalFlame** [comment]
> there's already a PR that changes the rcw bro, also yeah give a high tier role a mid/low tier weapon thats such a good idea

It has already been changed from MP5 to a Tommygun. I simply made a PR based on the suggestion for a replacement I was given.

**Comment by YosemiteYam** [comment]
Why the fuck are you removing the power gun from the legion POWER ROLE, they are meant to have a strong gun in this case the 14mm, its literally one slot, and is supposed to counter both the veteran rangers AMR and the heavy troopers POWER ARMOR and MINIGUN.

Get rid of this dogshit pr

**Comment by civilrightsact** [comment]
the assassin change is really, really heavyhanded. the thompson is not exactly a hit and run gun where an assassin isn't really staying around for return fire, its way too slow, and also, kind of common which sucks considering the assassin is meant to be p rare combatant all things considered?

**Comment by FantasticFwoosh** [comment]
I mean if MP5 is actually better for PVE than anything else, can't you just get into the habit of rushing bunkers for better guns instead of just charging headfirst into rangers? Just devil's advocate. I scarcely see legion contest with the efficacy of even the smallest NCR/Lance bunker looting trips.

On shotguns, recruits get a winchester double (the alternative is literally a fireaxe when we can craft bumper swords lmao), when really if you're ever going to bother, you really want your explorers and whoever to grab that city-killer blueprint.

**Comment by BigBigga** [comment]
the legion mald is unreal. 14mm needs to go. admin-spawn crutch gun with shotgun slug damage, SMG ROF, fully-auto, and rifle mag capacity? ok. axe it. 95% of the people who want it to stay are legion mains used to wiping 5-7 man lances with a few clicks in the enemy's general direction. make it a high-tier dungeon drop only. no faction should have it roundstart. a riot shotgun is far more fitting.

**Comment by BigBigga** [comment]
> Why the fuck are you removing the power gun from the legion POWER ROLE, they are meant to have a strong gun in this case the 14mm, its literally one slot, and is supposed to counter both the veteran rangers AMR and the heavy troopers POWER ARMOR and MINIGUN.
> 
> Get rid of this dogshit pr
> 
> (Also holy shit the fact that you first tried to replace it with an MP5 one of the weakest weapons ingame for the legion power role just shows how some people who code stuff in are so detached from the game sometimes)

Minigun is gone, replaced with a shitty flamer no one ever picks. SPA is dog if you don't know how to use it. 

It's **one** slot that can, with the barest amount of hand-eye coordination and the ability to press down a button, wipe out an entire faction, or a GOOD chunk of it, with very, very little risk on the attacker's side, as he can just bob and weave and backpedal while spraying and praying; getting hit, even once, by a stray 14MM bullet is a death sentence if you're not in actual power armor. 

I've seen it happen several times-- in most cases, I'd chalk it up to a skill issue, but in this case, in this very rare case, it isn't. Centurion gets an AMR, or, at least he did, not sure how that's like. 

Ultimately; will not be missed.

**Comment by VEN0M5** [comment]
> "admin spawn crutch gun"
> 
> It does less damage than most tier 3 and above calibers, it has LESS mag capacity than rifles (even the stacked magazines that you can print for them have less capacity then rifles magazines and they require 3 times the material usage), they have SMG fire rate that comes with smg RECOIL as well, thus aiming with them is dogshit compared to rifles.
> 
> SPA or Power Armour is not "dog", the real skill issue is dying in SPA and PA with r84s and or any other automatic that does just as much if not more damage then the 14mm to some assassin who has weak ass 26 bullet armor and then blaming the 14mm for it. You have more of a chance to kill people using SPA and any decent automatic as literally every robust tribal player has shown the past couple weeks with instances of players using tribalized PA and demolishing entire factions, something the legion does not and can not use. And theres multiple sets of power armor and salvaged PA that the NCR, BoS or any fucking rando can use against the legion.
> 
> While legion only gets "one" gun to fight against it.
> 
> Bad take, bad pr. Next!

14MM does 43 dmg, the calibers that out dmg it is .44, 45-70, 50bmg and gauss

**Comment by YosemiteYam** [comment]
> 14MM does 43 dmg, the calibers that out dmg it is .44, 45-70, 50bmg and gauss

Yes so it literally does less damage than tier 3 guns using .44, guns like brushies and hunting revolvers like 45-70 and WAY less damage than something like an AMR. The point is they don't do more damage than the high tier guns, some of which are also roundstart for other factions already. Its to illustrate that its great as its trying to have perceived, and has its own drawbacks. The biggest drawback being how bad the aiming and recoil is due to it being an smg.

**Comment by BigBigga** [comment]
ROF and magazine size is still a major factor. while it is true it doesn't do as much damage as the mentioned calibers, none of those calibers are able to be fired in full-auto, or 3-round burst (which the 14MM has); and with those calibers, your aim absolutely HAS to be good, or you'll be fucking yourself over due to either VERY low ROF or limited ammo, whereas with the 14MM, you have 27 rounds (with ext mags), and a full-auto/burst function. 

2 hits sums up to almost **90** dmg, and you still have 25 rounds left. there's literally no way around it, the 14MM, as is, is still broken, especially on a role like the assassin, who is fast as all hell.

**Comment by TheEternalFlame** [comment]
At request of Rebel-Man, The Venator sniper has been replaced wholesale with an AMR.

AND the 10mm SMG loadout has a ripper aswell.

**Comment by Serxule** [comment]
> At request of Rebel-Man, The Venator sniper has been replaced wholesale with an AMR.
> 
> AND the 10mm SMG loadout has a ripper aswell.

AMR is an incredibly slow and heavy gun and would make it an utterly useless loadout with how shitty assassin armor is, considering assassin literally relies fully on speed

**Comment by RicktenStone** [comment]
> At request of Rebel-Man, The Venator sniper has been replaced wholesale with an AMR.
> 
> AND the 10mm SMG loadout has a ripper aswell.

Just let them keep the fixed/buffed venator sniper, the assassin has light armor so if you give them an amr which has immense slowdown while moving and using, you're basically killing the only advantage of the assassins armor which is speed, makes no sense to give them an amr in that regard. It would just make them an incredibly easy target to kill versus someone like the veteran ranger for example that has an amr + heavy armor with high stats.

 Giving them the the fixed assassins sniper actually makes the role usable as a light sharpshooter that can shoot and move, while giving then an amr is..kind of shortsighted seeing as they cant even tank a couple bullets owing to having worse armor than even a typical veteran legionnaire. Makes the role kind of useless otherwise against other faction equivalents so I understand the frustration.

**Pull request merged**
