### PR TITLE
Armor PR - The Reckoning

### PR DESCRIPTION
**Pull request by Stutternov**
## About The Pull Request
**This is probably as good as I'm going to get it.** This PR has cost me so many braincells. I THINK all the armor sprites are working, I'll need to double-check, but this is nearly as good as I can get it after hours of sifting through crappy DMI files.

This re-organizes all armors back into their category files of light armor, medium armor, heavy armor, and power armor. Custom armor files are also added for suits and helmets to avoid custom armor cluttering our normal armor folders.

I've left base armor stats as a fallback for each path, giving all medium armors the path 'armor/medium/. . .' for example to ensure that ALL medium armors at least pull from what is determined **base level medium armor**, etc for each category. 

This will require me to go do **EVERY** loadout and armor path in the game over again more than likely, adding the new proper paths, but this will be good enough for a standardized system with easily malleable inputs. 

I am trying to access the rest of the code work I did for a repo with the same base-code so I can port the armor fixes needed alongside these armors, but I may have to wait on that. For now - this will be drafted till I can assure these work properly and until I can be screwed to go through EVERY armor item path in the game and re-path them.

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog
:cl:
removes: Some random old armors that we prob shouldn't use anyway.
adds: New armor-tier system properly and better organized keeping of acting faction, waster, and even custom armors.
/:cl:

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
Rebel is so back trying to balance the entirety of the game again, this is like... Atom Bomb or something!

**Comment by Stutternov** [comment]
> Rebel is so back trying to balance the entirety of the game again, this is like... Atom Bomb or something!

GET OUT OF MY HEAD GET OUT OF MY HEAD GET OUT OF MY HEAD GET OUT OF MY HEAD GET OUT OF MY HEAD GET OUT OF MY HEAD!!!!

**Comment by Stutternov** [comment]
Finally ready for testing.

**Comment by Zero-Percent-Angel** [comment]
Can you get the map CI stuff on this? :)

**Comment by AllCorruptingWyrm** [comment]
REEEEEEEEBELLL.
THE PR HAS A X MARK OF DEATH

**Pull request merged**
