### PR TITLE
The Return of Lil' Chew-Chew

### PR DESCRIPTION
**Pull request by panzerr1944**
## About The Pull Request

Brings the lil' man back to that one raider bunker in the depths z-level as an optional bossmob, including his old little cave area with ladder and everything. Figured the server could use more funny little challenges, and decided to re-add chew-chew following a chat with some people. If this gets added, i wish you all the best of luck.
image
(Also I made sure none of the other PRs really interacted with anything this one is editing)
((except laser.dm in the guns and ammo bloat pr, this also edits that file a bit))

## Pre-Merge Checklist
- [Y] You tested this on a local server.
- [Y] This code did not runtime during testing.
- [Y] You documented all of your changes.

## Changelog
:cl:
add: new extension to that one raider bunker
add: chew-chew laser upgrade
tweak: fixed up chew-chew to be more equivalent to the old version rather than the crappy new version- keep him a challenge.
balance: nerfed chew-chew hp and damage slightly
add: cool loot spawners
add: the ladder has a warning on its description. should have read the signs.,.,,.

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
Panzer's first PR try not to add a Lil' Chew-Chew dungeon challenge (FAILED, IMPOSSIBLE, NEVER ACCOMPLISHED)

**Comment by panzerr1944** [comment]
> Panzer's first PR try not to add a Lil' Chew-Chew dungeon challenge (FAILED, IMPOSSIBLE, NEVER ACCOMPLISHED)

worth. worth. worth. worth. worth.

**Comment by panzerr1944** [comment]
dnm yet, its having issues.

**Comment by panzerr1944** [comment]
will re-post soon

**Pull request closed without merging**
