### PR TITLE
Quirk Purge

### PR DESCRIPTION
**Pull request by Stutternov**
## About The Pull Request
Finally just tired of balancing quirks. Going to label these out simply here:

Positive perks:
- Fists of Steel: See Big Leagues; it's just a better Fists of Iron which is already annoying enough.

(Also increased spiritual and tagger cost to 1. You literally get 5 points to freely spend with no downside; so, use them.)

Negative perks:
- Spiderphobia - Dumb. It was a near effective free +2 points for just the downside of players yelling "SPIDER!!!" randomly to stun you.
- Maskphobia - Annoying, caused issues, certain things pathed as masks or not as masks, etc. 
- Catphobia - See spiderphobia but even MORE free points.
- Eyephobia - See above phobias. Same issue.

Neutral perks:
- Masochism - Caused people to cum on the ground with a literal cum decal. Why the fuck.

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog
:cl:
removes: see about; tons of perks removed.
/:cl:

### CODE REVIEW

**Comment by Zero-Percent-Angel** [comment]
While I am not going to stand in the way of quirk changes, I do think we need to have a think about what space quirks should be filling and what they should be granting people. 
I will admit I like the theory of things like chem-wiz, a perk that gives you a specific boost within a skill domain (but not to the entire domain) without having to invest in that area heavily.

**Comment by Stutternov** [comment]
> While I am not going to stand in the way of quirk changes, I do think we need to have a think about what space quirks should be filling and what they should be granting people.
> I will admit I like the theory of things like chem-wiz, a perk that gives you a specific boost within a skill domain (but not to the entire domain) without having to invest in that area heavily.

I was requested by staff to remove that one but I’ll reverse the Chem whiz one if you want to keep it. I’d need to unlock crafting anyway I just remembered if I did so.

The rest, especially phobias, need to go.

**Comment by X404ErrorX** [comment]
Stop nerfing melee and unarmed bro, in a fight with more than 2 or 3 people there is no way to use melee, it's already very bad, the last PR removed the stamina damage so now it's even worse, there are people who likes to use the melee and unarmed, but all thoes PRs are turning it useless.

Most weapons are capable of killing you in 2 or 3 shots (amr just need one shot to critic you, also if they hit your legs you are fucked), someone who has to risk using fast armor has to hit their target more times than someone who shoots from distance does not make sense.

**Comment by Serxule** [comment]
melee and unarmed are already weaker than ballistics in the majority of fights, why does it need nerfs, along with trekker removal not making sense, considering most people who **live in the wasteland** arent going to have problems trekking. not to mention these books arent even able to be found anymore, why do you think they're quirks now

**Comment by Stutternov** [comment]
The quirk system of perk selection was a mistake. Mashallah.

**Comment by Stutternov** [comment]
> melee and unarmed are already weaker than ballistics in the majority of fights, why does it need nerfs, along with trekker removal not making sense, considering most people who **live in the wasteland** arent going to have problems trekking. not to mention these books arent even able to be found anymore, why do you think they're quirks now
> 
> oh and its not like these are free quirks, big leagues takes 3 points, fists of steel takes 3 points, trekker takes 3 points
> 
> if you're tired of balacing, leave it to someone else, instead of being an asshat and just deleting everything because you're lazy

I will work on more pressing Prs, sadly I am unable to code in your fathers love. You may have to find that elsewhere.

**Comment by Omnisalad** [comment]
Phobias 100% need to go, literally just stat stick traits that get ignored or get spammed with "SPIDERS, SKELETONS, EYES, CATS!!" over the radio or in the middle of a fight, gameplay was just dumb surrounding these.

Surgery/Chem perks existing to dodge skill requirements is weird, if we're going to use the skill system we shouldn't be leaving in ways to bypass it just for the sake of it, seems like a fair removal.

As for the Melee traits I don't have an opinion from the position of someone who uses them for PvP. All I know is that from how you've explained it is that these perks are stacking, and it's making melee ludicrously powerful.

Trekker getting axed in favor of normalized move speed on all terrains is a change I can learn to love from an accessibility standpoint, however there is a part of me that'd like for it to stick around, mostly just so people who don't have trekker are more obligated to take roads to avoid slowdown, but as it stands it's almost used by everyone to avoid slowdown in combat.

Masochism should just have it's weird ERP mechanics axed and reintroduced as a positive perk that gives increased mood for being hurt, maybe with a cost of 1 or 2, but until the weird cum thing is removed I'd say this change is for the better.

**Comment by Serxule** [comment]
> Masochism should just have it's weird ERP mechanics axed and reintroduced as a positive perk that gives increased mood for being hurt, maybe with a cost of 1 or 2, but until the weird cum thing is removed I'd say this change is for the better.

i feel like most people will agree on this being a no because mood has a huge affect on your speed, which would make it a meta perk

**Comment by Stutternov** [comment]
> As for the Melee traits I don't have an opinion from the position of someone who uses them for PvP. All I know is that from how you've explained it is that these perks are stacking, and it's making melee ludicrously powerful.

The listed reason for this one was due to stacking and, depending on how it stacks, when trying to balance melee weapons (something on the back burner for.. a bit now..) I have to account for when a player takes a perk vs when they don't; a weapon that is decent for a normal player may end up with ~30% extra damage due to a stacking of perks, skill, and drugs - if not higher (I believe you can get an estimated 40% increase in total melee damage depending on the weapon and perks). This means I have to balance around people with high-end stats. I did leave little league since it.. stacks _less_, it still makes it annoying but it wouldn't result in as much broken gear.

> Trekker getting axed in favor of normalized move speed on all terrains is a change I can learn to love from an accessibility standpoint, however there is a part of me that'd like for it to stick around, mostly just so people who don't have trekker are more obligated to take roads to avoid slowdown, but as it stands it's almost used by everyone to avoid slowdown in combat.

I'm mixed on tracker, I have nostalgia for Fortuna and Lonestar's system where all tile slowdowns, besides water, was fully removed. It feels a lot more smoother and, honestly, plays into TG station's strengths of 'smooth movement'; armors already provide enough slowdown and Trekker acts.. weird with armors sometimes. I've had people test it out for me but I get mixed results between: "I see no difference" to "It seems to make my armor slightly faster even on roads?" - so I'm not sure which it is as the code is not there.

None the less, I'd argue removing of slowdown on tiles would be a good thing. And thus Trekker would go away anyway with that. (I need to do the PR separately, it's why I didn't check this PR off yet so I can go do that PR separate and have both up at once to avoid conflicts incase.)

**Pull request merged**
